apiVersion: argoproj.io/v1alpha1

kind: Application

metadata:
  name: platform-postgres
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"

spec:
  project: "default"
  source:
    repoURL: https://github.com/nolannguyen1212/mini-k8s-infra.git
    targetRevision: master
    path: apps/platform/postgres
  destination:
    server: https://kubernetes.default.svc
    namespace: platform
  syncPolicy:
    automated: { prune: true, selfHeal: true }
    syncOptions: ["CreateNamespace=true"]
