apiVersion: v1

kind: Secret

metadata:
  name: miniflux-secret
  namespace: miniflux

type: Opaque

stringData:
  DATABASE_URL: "postgres://miniflux:dev-miniflux-db-password@postgres.platform.svc.cluster.local:5432/miniflux?sslmode=disable"
  ADMIN_USERNAME: admin
  ADMIN_PASSWORD: dev-admin-password
